### ISSUE TITLE
Xóa nhãn hiệu

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#106]
Thiết Kế:
- Thiết kế dạng bảng có cột theo bootstrap với phần tạo danh mục nằm bên trên bảng
- các cột được chia ra theo ID, Mã danh mục, nhãn hiệu, xuất xứ, thao tác 
- Phần chỉnh sửa thiết kế theo dạng form gồm có mã danh mục, nhãn hiệu, xuất xứ 
Dữ Liệu: 
- lấy dữ liệu từ bảng catalog 
Xử Lý:
- Từ mục quản lý sản phẩm bên sidebar, nhấn vào danh sách danh mục 
- Từ đó chuyển tới trang tạo danh mục,  từ trong trang hiện ra bảng danh mục, trong bảng có các chức năng edit, delete, details
- Nhấn vào edit thì chuyển tới trang form chỉnh sửa

**Comment by harutoakira** [comment]
đã hoàn thành
