### ISSUE TITLE
Báo cáo doanh thu

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#122]
**Thiết kế**
Thống kê cửa hàng theo dạng số liệu thống kê theo biểu đồ đặt trong giao diện quản trị viên và nhân viên bán hàng
**Dữ liệu**
Dữ liệu được lấy từ đơn hàng 
**Xử lí**
Quản trị viên sau khi đăng nhập vào giao diện admin ấn vào mục "Thống kê doanh thu"

**Comment by lhthinh** [comment]
Đã nhận task
