### ISSUE TITLE
Xem danh sách nhân viên

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#22]
**Thiết kế**
Màn hình danh sách nhân viên bao gồm các cột ID, họ tên nhân viên, ảnh , địa chỉ, ngày sinh, giới tính, sđt , chức vụ, tính năng
Phía trên danh sách nhân viên có ô tìm kiếm 
**Dữ liệu**
Dữ liệu sẽ được lấy từ bảng NhanVien để hiển thị danh sách các nhân viên
**Xử lí**
Sau khi admin đăng nhập, ấn vào  "phần quản lí nhân viên" bên trái màn hình sẽ chuyển đến trang danh sách nhân viên, từng dữ liệu của nhân viên sẽ hiển thị trên từng dòng tương ứng với các cột, tính năng bao gồm: xóa và chỉnh sủa thông tin nhân viên

**Comment by nhanne** [comment]
Đã hoàn thành code bởi Thắng trước khi push lên github

**Comment by Hade16062002** [comment]
Đã nhận

**Comment by Hade16062002** [comment]
Đã hoàn thành
