### ISSUE TITLE
Tìm kiếm nhân viên

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#25]
**Thiết kế**
Textbox tìm kiếm được đặt trên danh sách nhân viên

**Dữ liệu**
Tìm kiếm nhân viên thông qua tên hoặc số điện thoại nhân viên

**Xử lí**
Sau khi đăng nhập thành công vào giao diện admin, người dùng điền tên hoặc số điện thoại muốn tìm kiếm vào ô TextBox và ấn enter sẽ cập nhật lại danh sách nhân viên bên dưới tương ứng với dữ liệu được nhập vào ô tìm kiếm

**Comment by lhthinh** [comment]
Done code tìm kiếm nhân viên

**Comment by lhthinh** [comment]
Đã nhận task

**Comment by lhthinh** [comment]
Đã hoàn thành
