### ISSUE TITLE
Tìm kiếm sản phẩm trong admin

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#31]
**Thiết kế**

Thanh "tìm kiếm" được đặt ngoài cùng bên phải của danh sách đơn hàng.

**Dữ liệu**

Dữ liệu tìm kiếm dựa trên "mã sản phẩm" của sản phẩm.

**Xử lý**

Sau khi đăng nhập thành công tài khoản Admin, chuyển đến trang quản lý sản phẩm ta thấy ô "tìm kiếm" được đạt trên danh sách sản phẩm. Khi nhập dữ liệu vào và nhấn "enter" sẽ hiện thị sản phẩm tương ứng với dữ liệu nhập vào.

**Comment by PhamDuy2506** [comment]
Code đã được hoàn thành bởi Pham Duy2506 trước khi push lên github.
