### ISSUE TITLE
Chấp nhận đơn hàng

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#37]
Thiết kế
chia thiết kế theo kiểu grid 6 6
Đơn hàng nằm ở bên trái và chi tiết đơn hàng ở bên phải
Button xác nhận đơn hàng nằm ở dưới form chỉ tiết đơn hàng
Dữ liệu
Dữ liệu của đơn hàng được trả ra view
Xử lí
Khi người dùng ấn vào chấp nhận đơn hàng ở trang list sẽ vào trang chấp nhận có dữ liệu của đơn hàng đó và nút xác nhận đơn hàng sẽ hiển thị ở status chưa giao hàng sau đó người dùng ấn button đó thì status sẽ hiển thị là đang giao hàng

**Comment by lhthinh** [comment]
done code phần tạo đơn hàng

**Comment by lhthinh** [comment]
Đã nhận task

**Comment by lhthinh** [comment]
Đã hoàn thành
