### ISSUE TITLE
Hủy đơn hàng

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#38]
Thiết kế
chia thiết kế theo kiểu grid 6 6
Đơn hàng nằm ở bên trái và chi tiết đơn hàng ở bên phải
Button xác nhận đơn hàng nằm ở dưới form chỉ tiết đơn hàng
Button hủy đơn hàng nằm dưới button xác nhận đơn hàng
Dữ liệu
Dữ liệu của đơn hàng được trả ra view
Xử lí
Khi người dùng ấn vào button hủy đơn hàng, trạng thái đơn hàng sẽ chuyển sang đã hủy

**Comment by lhthinh** [comment]
Đã nhận task

**Comment by lhthinh** [comment]
Đã hoàn thành
