### ISSUE TITLE
Tìm kiếm khách hàng bằng email

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#41]
**Thiết kế**

Thanh "Tìm kiếm" được đặt ngoài cùng bên phải của danh sách đơn hàng.
**Dữ liệu **

Dữ liệu tìm kiếm dựa trên email khách hàng.
**Xử lý**

Sau khi đăng nhập thành công tai khoản admin, sẽ chuyển đến trang quản lý đơn hàng. Khi nhập dữ liệu vào thanh tìm kiếm và nhấn "enter" sẽ hiện thị những đơn hàng tương ứng với dữ liệu được nhập.

**Comment by PhamDuy2506** [comment]
Code đã được hoàn thành bởi Pham Duy2506 trước khi push lên github.
