### ISSUE TITLE
Đăng nhập và đăng xuất

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#45]
**Giao diện được thiết kế theo dạng form bao gồm:**
+Email, mật khẩu, button "trở lại" và button "đăng nhập"
Button "Đăng xuất" được đặt ở mục cuối cùng trong menu khi lia chuột vào avatar 
**Dữ liệu**
Dữ liệu kiểm tra qua bảng KhachHang
Khi đăng nhập thành công, dữ liệu lưu vào session của trang web
**Xử lí**
Khi khách hàng điền đầy đủ thông tin vào form người dùng ấn vào button "đăng nhập", dữ liệu sẽ được kiểm tra nếu Email và mật khẩu trùng khớp với dữ liệu có trong hệ thống sẽ cho phép người dùng vào trang chủ cửa hàng với tài khoản của mình, nếu dữ liệu không trùng khớp thì sẽ hiện lỗi "Email hoặc mật khẩu không đúng, vui lòng thử lại"
Khi ấn vào button đăng xuất, dữ liệu người dùng sẽ bị xóa khỏi cookie trang web

**Comment by PhatOnggg2912** [comment]
accept

**Comment by PhatOnggg2912** [comment]
Giao diện được thiết kế theo dạng form của bootstrap bao gồm:
+Email, mật khẩu
+Bên dưới form có button "trở lại" để quay về trang chủ và button "đăng nhập" đặt bên cạnh
Dữ liệu
Dữ liệu người dùng được lưu trữ vào session nếu đăng nhập thành công
Xử lí
Khi khách hàng điền đầy đủ thông tin vào form người dùng ấn vào button "đăng nhập", dữ liệu sẽ được kiểm tra nếu Email và mật khẩu trùng khớp với dữ liệu có trong hệ thống sẽ cho phép người dùng vào trang chủ cửa hàng với tài khoản của mình, nếu dữ liệu không trùng khớp thì sẽ hiện lỗi "Email hoặc mật khẩu không đúng, vui lòng thử lại"
