### ISSUE TITLE
Xóa toàn bộ giỏ hàng

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#52]
Thiết kế
Button "Xóa giỏ hàng" được đặt phía dưới cùng bên phải của danh sách các sản phẩm có trong giỏ hàng
Dữ liệu
Giỏ hàng phải có sản phẩm trong đó thì mới hiển thị button
Xử lí
Khi người dùng vào trang giỏ hàng, ấn vào button "Xóa giỏ hàng", toàn bộ sản phẩm có trong giỏ hàng sẽ được xóa khỏi giỏ hàng

**Comment by PhatOnggg2912** [comment]
Merged to main!
