### ISSUE TITLE
Xóa sản phẩm khỏi giỏ hàng

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#53]
Thiết kế
Button xóa sản phẩm khỏi giỏ hàng được đặt trong mục thao tác trên trang giỏ hàng của từng sản phẩm
Dữ liệu

Xử lí
Sau khi thêm sản phẩm vào giỏ hàng, khách hàng vào trang giỏ hàng xem danh sách những sản phẩm được thêm vào , khi khách hàng ấn vào button xóa trong mục thao tác , sản phẩm tương ứng sẽ bị xóa khỏi giỏ hàng

**Comment by PhatOnggg2912** [comment]
Merged to main
