### ISSUE TITLE
Cập nhật số lượng sản phẩm có trong giỏ hàng

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#54]
**Thiết kế** 
ô cập nhật số lượng trong chi tiết giỏ hàng thiết kế dưới dạng text input 
**Dữ liệu**
Dữ liệu các sản phẩm người dùng ấn thêm vào giỏ hàng
**Xử lí**
Người dùng nhập số lượng sản phẩm muốn cập nhật sau đó blur ra ngoài hoặc ấn enter

**Comment by lhthinh** [comment]
Đã nhận task

**Comment by lhthinh** [comment]
Đã hoàn thành
