### ISSUE TITLE
Hiển thị trang thông tin cá nhân

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#57]
**Thiết kế**
Màn hình hồ sơ cá nhân bao gồm hai cột:
•	Một bên là thông tin cá nhân bao gồm: Email, họ tên, mật khẩu, số điện thoại, địa chỉ, số CMT, ngày sinh và button "Sửa hồ sơ" được đặt bên dưới
•	Một bên hiển thị ảnh đại diện của khách hàng

**Dữ liệu**
Dữ liệu thông tin khách hàng được lấy từ bảng Khach hang

**Xử lí**
Sau khi đăng nhập thành công, khách hàng đưa chuột lên avatar trên thành navbar, sau đó khách hàng ấn vào mục "Hồ sơ tài khoản" để chuyển đến trang hồ sơ tài khoản.
Khi ấn vào button "Sửa hồ sơ" trang sửa thông tin cá nhân sẽ được hiển thị.

**Comment by PhamDuy2506** [comment]
Đã nhận
