### ISSUE TITLE
Thay đổi mật khẩu tài khoản

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#58]
Giao diện:
Hiển thị form thay đổi mật khẩu của tài khoản bao gồm: Mật khẩu cũ, Mật khẩu mới và Xác nhận mật khẩu mới
Có button chấp nhận và button quay về

Dữ liệu:
Dữ liệu lấy theo id của người dùng và đổ lên các input trong form

Xử lí:
Khi người dùng truy cập vào trang sửa mật khẩu thì hiển thị lên form chỉnh sửa sau đó người dùng chỉnh sửa mật khẩu và ấn vào chấp nhận nếu người dùng muốn quay lại không thay đổi mật khẩu thì ấn quay lại

**Comment by lhthinh** [comment]
Đã hoàn thành
