### ISSUE TITLE
Đăng nhập admin

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#62]
Thiết kế
Màn hình đăng nhập bao gồm hai ô Email và mật khẩu và button đăng nhập được đặt giữa màn hình
Dữ liệu
Dữ liệu đăng nhập được lấy từ bảng NhanVien
Xử lí
Người dùng truy cập trang đăng nhập admin điền Email và mật khẩu, sau đó ấn vào button đăng nhập, nếu thông tin trùng khớp sẽ chuyển đến giao diện admin, ngược lại sẽ hiển thị lỗi "Không phải tài khoản admin"

**Comment by PhatOnggg2912** [comment]
Đã nhận!

**Comment by PhatOnggg2912** [comment]
Da hoan thanh!
