### ISSUE TITLE
Tìm kiếm sản phẩm

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#63]
**Thiết kế** 
Thanh tìm kiếm được thiết kế theo dạng textbox đặt giữa trên header 
**Dữ liệu**
Dữ liệu tìm kiếm theo tên sản phẩm hoặc danh mục sản phẩm
**Xử lí**
Người dùng nhập thông tin sản phẩm cần tìm vào ô tìm kiếm và nhấn enter hoặc ấn vào button "tìm kiếm" , danh sách sản phẩm sẽ được cập nhật lại dựa theo dữ liệu được nhập vào.

**Comment by lhthinh** [comment]
Đã nhận task

**Comment by lhthinh** [comment]
Đã hoàn thành
