### ISSUE TITLE
Thêm nhãn hiệu mới

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#65]
Thiết Kế
- Trong tạo mới danh mục được thiết kế kiểu cột sử dụng bootstrap chia ra thành 5 cột ( mỗi cột có ID, Mã danh mục,nhãn hiệu,Xuất xứ,Thao Tác )
Dữ Liệu
- Lấy danh mục từ trong bảng Catalog của SQL 
Xử Lý
- trong bảng danh sách sản phẩm nhấn vào button để tạo mới sản phẩm 
- từ trong trang tạo mới sản phẩm có button ( Thêm danh mục ) nằm trên form tạo mới sản phẩm
- Click vào button "Tạo mới danh mục " thì  chuyển tới trang tạo mới danh mục

**Comment by harutoakira** [comment]
đã nhận

**Comment by harutoakira** [comment]
Đã hoàn thành
