### ISSUE TITLE
Hiển thị giao diện admin

### ISSUE THREAD

**Issue by nhanne** [nhanne/SmartPhone#66]
Thiết kế
- trang đăng nhập tài khoản admin được thiết kế dạng form của boostrap, gồm có login và password cùng với form dưới dòng password là button đăng nhập
- thị giao diện chính của admin trong đó có: sidebar(quản lý nhân viên, khách hàng, sản phẩm, đơn hàng), headbar(có logout button), body
Dữ liệu

Xử lý
- Sau khi nhập tài khoản và password vào form đăng nhập và bấm button, dữ liệu sẽ được kiểm tra nếu tài khoản và mật khẩu trùng khớp với dữ liệu có trong hệ thống sẽ cho phép người dùng vào trang chủ cửa hàng với tài khoản của mình, nếu dữ liệu không trùng khớp thì sẽ hiện lỗi "Email hoặc mật khẩu không đúng, vui lòng thử lại" 
- sau khi đăng nhập thành công sẽ chuyển đến trang giao diện của admin nơi chứa các thông tin của cửa hàng

**Comment by harutoakira** [comment]
đã nhận

**Comment by harutoakira** [comment]
đã hoàn thành
